import type { Metadata } from 'next';
import './globals.css';
import { helios, onest } from '@/theme/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className="scroll-smooth"
    >
      <body className={`${onest.variable} ${helios.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
